name: "Scan containers"
on:
  push:
#  schedule:
#    # every night at one
#    - cron:  '0 1 * * *'
#  workflow_dispatch:

jobs:
  get-containers:
    name: Get containers from submodules
    runs-on: ubuntu-latest
    outputs:
      container-matrix: ${{ steps.submodules.outputs.containers }}
    steps:
      - uses: actions/checkout@master

      - name: Get docker images for submodules
        id: submodules
        uses: FIWARE-Ops/get-images-from-submodules@master

  scan-container:
    name: Scan
    runs-on: ubuntu-latest
    needs: ["get-containers"]

    strategy:
      fail-fast: false
      matrix:
        containers: ${{fromJson(needs.get-containers.outputs.container-matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: Execute container scan
        continue-on-error: true
        run: |
          .github/container-scan.sh ${{ matrix.containers }}

      - name: Extract artifact name
        id: ean
        run: |
          imageName=(${${{ matrix.containers }}//:/})[0]
          imageVersion=(${${{ matrix.containers }}//:/})[1]
          echo "::set-output name=name::${imageName}"
          echo "::set-output name=version::${imageVersion}"
      

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.ean.outputs.name }}-${{ steps.ean.outputs.version }}
          path: ./reports/